SF:lib/core/errors/exceptions.dart
DA:4,1
DA:9,0
DA:10,0
LF:3
LH:1
end_of_record
SF:lib/core/errors/failure.dart
DA:5,1
DA:10,1
DA:11,3
DA:15,1
DA:17,4
LF:5
LH:5
end_of_record
SF:lib/src/authentication/data/datasources/authentication_remote_datasource.dart
DA:16,0
DA:19,0
DA:22,0
DA:25,0
LF:4
LH:0
end_of_record
SF:lib/src/authentication/data/repository/authentication_repository_implementation.dart
DA:13,1
DA:17,1
DA:30,2
DA:33,1
DA:34,2
DA:38,1
DA:41,2
DA:42,0
DA:43,1
DA:44,2
LF:10
LH:9
end_of_record
SF:lib/src/authentication/domain/entities/user.dart
DA:4,0
DA:11,0
DA:12,0
DA:24,0
DA:25,0
LF:5
LH:0
end_of_record
SF:lib/src/authentication/data/models/user_model.dart
DA:7,0
DA:14,0
DA:15,0
DA:22,0
DA:23,0
DA:25,0
DA:27,0
DA:28,0
DA:29,0
DA:30,0
DA:31,0
DA:32,0
DA:35,0
DA:36,0
DA:37,0
DA:38,0
DA:39,0
DA:42,0
DA:48,0
DA:49,0
DA:50,0
DA:51,0
DA:52,0
LF:23
LH:0
end_of_record
SF:lib/src/authentication/domain/repositories/authentication_repository.dart
DA:5,0
LF:1
LH:0
end_of_record
